#!/bin/sh

set -e

if [ -x /usr/bin/update-menus ] ; then
  update-menus
fi

update-alternatives --quiet --install /usr/bin/editor editor /usr/bin/the 10\
  --slave /usr/share/man/man1/editor.1.gz editor.1.gz \
          /usr/share/man/man1/the.1.gz
