/*
 * THE - The Hessling Editor. A text editor similar to VM/CMS xedit.
 * Copyright (C) 1991-2026 Mark Hessling
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to:
 *
 *    The Free Software Foundation, Inc.
 *    675 Mass Ave,
 *    Cambridge, MA 02139 USA.
 *
 *
 * If you make modifications to this software that you feel increases
 * it usefulness for the rest of the community, please email the
 * changes, enhancements, bug fixes as well as any and all ideas to me.
 * This software is going to be maintained and enhanced as deemed
 * necessary by the community.
 *
 * Mark Hessling,  M.Hessling@qut.edu.au  http://www.lightlink.com/hessling/
 */

/*
$Id: thedefs.h,v 1.22 2022/10/23 21:57:53 mark Exp $
*/

#ifndef THE_THEDEFS_H
#define THE_THEDEFS_H

#ifndef TRUE
# define TRUE 1
#endif
#ifndef FALSE
# define FALSE 0
#endif

/*---------------------------------------------------------------------*/
/* Include config.h generated by configure.                            */
/*---------------------------------------------------------------------*/
#ifdef HAVE_CONFIG_H
# include "config.h"
#else
# define BUILD3001 1
# define RETSIGTYPE void
# define STDC_HEADERS 1
#endif

#if defined(_WIN32) && !defined(WIN32)
# define WIN32 1
#endif

/*
 * Terminal capability macros derived from build/platform selections. Keep
 * these out of the editor umbrella header; physical terminal implementations
 * lower the behavior privately through the driver layer.
 */
#if defined(USE_XCURSES)
# if defined(SIGWINCH) && defined(HAVE_RESIZE_TERM)
#  define CAN_RESIZE 1
# endif
# define PDCURSES_MOUSE_ENABLED 1
#endif

#if defined(USE_SDLCURSES)
# define CAN_RESIZE 1
# define PDCURSES_MOUSE_ENABLED 1
#endif

#if defined(USE_VTCURSES)
# define CAN_RESIZE 1
#endif

#if defined(USE_NCURSES) && defined(SIGWINCH) && defined(HAVE_RESIZETERM)
# define CAN_RESIZE 1
#endif

#if defined(PDCURSES_MOUSE_ENABLED) || defined(USE_NCURSES)
# define THE_MOUSE_ENABLED 1
#endif

#if defined(HAVE_SLK_INIT)
# if defined(__PDCURSES__)
#  define MAX_SLK    12
#  define MAX_SLK_FORMAT 5
# elif defined(USE_NCURSES)
#  define MAX_SLK    12
#  define MAX_SLK_FORMAT 4
# else
#  define MAX_SLK     8
#  define MAX_SLK_FORMAT 2
# endif
#else
# define MAX_SLK      0
# define MAX_SLK_FORMAT 2
#endif

/*
 * Legacy Windows console handoff used by WinGUI/SDL curses builds.
 */
#if defined(USE_WINGUICURSES) || (defined(USE_SDLCURSES) && defined(_WIN32))
# include <windows.h>
# undef MOUSE_MOVED
extern int gotOutput;
extern void StartupConsole( void );
extern void ClosedownConsole( int );
# define STARTUPCONSOLE() StartupConsole()
# define CLOSEDOWNCONSOLE(x) ClosedownConsole(x)
# define DISPLAY_ERROR(a,b,c,d) STARTUPCONSOLE();display_error(a,b,c);CLOSEDOWNCONSOLE(d)
# define HIT_ANY_KEY "** Command completed **"
#else
# define STARTUPCONSOLE()
# define CLOSEDOWNCONSOLE(x)
# define DISPLAY_ERROR(a,b,c,d) display_error(a,b,c)
# define HIT_ANY_KEY "Hit any key to continue..."
#endif

/*---------------------------------------------------------------------*/
/* The following values can be changed to suit your needs.             */
/*---------------------------------------------------------------------*/
#define MAX_FILE_NAME             1000  /* maximum length of fully qualified file */
#define MAX_LENGTH_OF_LINE        1000  /* default maximum length of a line */
#define MAX_COMMANDS                10  /* default maximum number of commands allowed on command line */
#define MAX_RECV                    20  /* number of lines that can be recovered */
#define MAX_SAVED_COMMANDS          20  /* number of commands that can be retrieved */
#define MAX_NUMTABS                 32  /* number of tab stops that can be defined */
#define MAXIMUM_POPUP_KEYS          20  /* maximum number of keys in popup menu */
#define MAXIMUM_DIALOG_LINES       100  /* maximum number of lines in a dailog */

/*---------------------------------------------------------------------*/
/* The following values should not be changed unless you know what you */
/* are doing !                                                         */
/*---------------------------------------------------------------------*/
typedef unsigned short ROWTYPE;
typedef unsigned short COLTYPE;
typedef unsigned char  CHARTYPE;
typedef long           LENGTHTYPE; /* was unsigned short */ /* MUST be signed!!! */
typedef long           LINETYPE;
typedef unsigned short SELECTTYPE;
/*---------------------------------------------------------------------*/
/* A default char type to avoid compiler warnings.                     */
/*---------------------------------------------------------------------*/
typedef char           DEFCHAR;

#endif
